CREATE DATABASE IF NOT EXISTS poll;
use poll;

CREATE TABLE IF NOT EXISTS questions(
	QuestionID VARCHAR(30) PRIMARY KEY,
  QuestionText VARCHAR(500) NOT NULL,
);

CREATE TABLE IF NOT EXISTS answers(
	AnswerID VARCHAR(30) PRIMARY KEY,
  AnswerText VARCHAR(500) NOT NULL,
  QuestionID VARCHAR(30) NOT NULL,
  Votes INT NOT NULL
  FOREIGN KEY (QuestionID)
    REFERENCES questions(QuestionID)
);